# Generated by Django 5.1.7 on 2025-03-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
