# Generated by Django 5.1.7 on 2025-03-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='content',
            field=models.TextField(default='Servicio en construcción', verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
