# Generated by Django 5.1.7 on 2025-03-31 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images', verbose_name='Imagen')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='services.services')),
            ],
            options={
                'verbose_name': 'Imagen de servicio',
                'verbose_name_plural': 'Imágenes de servicio',
            },
        ),
    ]
